apiVersion: v1beta1
kind: ApplianceConfig
ocpRelease:
  # OCP release version in major.minor or major.minor.patch format
  # (in case of major.minor - latest patch version will be used)
  # If the specified version is not yet available, the latest supported version will be used.
  version: "{{ ocp_release_version }}"
  # OCP release update channel: stable|fast|eus|candidate
  # Default: stable
  # [Optional]
  channel: "{{ ocp_release_channel }}"
  # OCP release CPU architecture: x86_64|aarch64|ppc64le
  # Default: x86_64
  # [Optional]
  cpuArchitecture: "{{ cpu_architecture }}"
# If specified, should be at least 150GiB.
# If not specified, the disk image should be resized when 
# cloning to a device (e.g. using virt-resize tool).
# [Optional]
#diskSizeGB: '{{ disk_size_gb }}'
# PullSecret required for mirroring the OCP release payload
pullSecret: '{{ pull_secret }}'
# Public SSH key for accessing the appliance during the bootstrap phase
# [Optional]
sshKey: "{{ ssh_key }}"
# Password of user 'core' for connecting from console
# [Optional]
userCorePass: "{{ user_core_pass }}"
# Local image registry details (used when building the appliance)
# [Optional]
#imageRegistry:
  # The URI for the image
  # Default: docker.io/library/registry:2
  # Alternative: quay.io/libpod/registry:2.8
  # [Optional]
#  uri: "uri"
  # The image registry container TCP port to bind. A valid port number is between 1024 and 65535.
  # Default: 5005
  # [Optional]
#  port: "port"
# Enable all default CatalogSources (on openshift-marketplace namespace).
# Should be disabled for disconnected environments.
# Default: false
# [Optional]
enableDefaultSources: false
# Stop the local registry post cluster installation.
# Note that additional images and operators won't be available when stopped.
# Default: false
# [Optional]
stopLocalRegistry: false
# Additional images to be included in the appliance disk image.
# [Optional]
# additionalImages:
#   - name: image-url
# Operators to be included in the appliance disk image.
# See examples in https://github.com/openshift/oc-mirror/blob/main/docs/imageset-config-ref.yaml.
# [Optional]
# operators:
# - catalog: catalog-uri
#   packages:
#     - name: package-name
#       channels:
#         - name: channel-name
